version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/html
    env_file:
      - .dev.vars
    ports:
      - "5173:5173"
      - "8788:8788"
    command: bun run dev:client
